- project:
    check: &jobs
      jobs:
        - haskell-stack-test:
            vars:
              lts_version: lts-16.5
            nodeset:
              nodes:
                - name: container
                  label: pod-haskell-lts-16
        - hlint:
            nodeset:
              nodes:
                - name: container
                  label: pod-haskell-f32
    gate: *jobs
